---
title: "Research"
---

I have two main active research programs: ethical issues related to AI and moral responsibility. 

My AI ethics research seeks to understand how, when, and whether to deploy AI technologies in morally defensible ways. 

My moral responsiiblity research aims to articulate a comprehensive theory of moral responsibility: an account of the nature and norms of holding people morally responsible. I approach these issues with a distinctive, interdisciplinary methodology. I maintain that any adequate theory of moral responsibility must attend to philosophical argument as well as results from the empirical sciences. In my published work I solve a vexing problem for extant accounts of trust, invoke psychological work on the blaming emotions to show that we have several different conceptions of moral responsibility, pull from a variety of empirical and philosophical sources to develop a nuanced account of angry virtue and vice, articulate the grounds on which emotions like resentment and indignation are deserved by their targets, develop a plausible theory of punishment’s justification, and explain how forgiveness can be both possible and warranted.

### REFEREED JOURNAL ARTICLES

* **Reasons to Punish Autonomous Robots.** [The Gradient](https://thegradient.pub/reasons-to-punish-autonomous-robots/){target="_blank"} 2023. Archive at [PhilPapers](https://philpapers.org/rec/COGRTP){target="_blank"}.
* **Developing an objective measure of knowledge of factory farming.** [Philosophical Psychology](https://doi.org/10.1080/09515089.2022.2056436){target="_blank"} 2022. With Adam Feltz, Jacob N. Caton, Mylan Engel, Silke Feltz, Ramona Ilea, L. Syd M Johnson & Tom Offer-Westort. Archive at [TaylorAndFrancisOnline](https://www.tandfonline.com/eprint/HUDMVGSJUPKYUTX7XEDB/full?target=10.1080/09515089.2022.2056436){target="_blank"} and [PhilPapers](https://philpapers.org/rec/FELDAO-2){target="_blank"}.
* **Educational interventions and animal consumption: Results from lab and field studies.** [Appetite](https://www.sciencedirect.com/science/article/abs/pii/S0195666322000721){target="_blank"} Volume 173, 1 June 2022, 105981. With Adam Feltz, Jacob N. Caton, Mylan Engel, Silke Feltz, Ramona Ilea, L. Syd M. Johnson, Tom Offer-Westort, Rebecca Tuvel. Archive at [PhilPapers](https://philpapers.org/rec/FELEIA){target="_blank"}.
* [**Forgiveness and the Multiple Functions of Anger.**](https://drive.google.com/file/d/1I_iLakxNjelo0S-_x8UGhdA_aTLb_3Vx/view?usp=sharing){target="_blank"} 2019. With Aumann, Antony G. [Journal of Philosophy of Emotion](https://www.jpeonline.org/issues/2019-volume-1-no-1-winter){target="_blank"} 1, no. 1: 44-71. [Audio](https://drive.google.com/file/d/1c1uogW3pSawTHOUrkPN8xiOesO513Cg0/view?usp=sharing){target="_blank"}. Archive at [PhilPapers](https://philpapers.org/rec/AUMFAT){target="_blank"}
* **Fortifying the Self-Defense Justification of Punishment.** 2017. [Public Affairs Quarterly](https://scholarlypublishingcollective.org/uip/paq/issue/31/4){target="_blank"}, 31.4, October. Archive at [PhilPapers](https://philpapers.org/rec/ZACFTS-2){target="_blank"}
* **Rolling Back the Luck Problem for Libertarianism.** 2015. [Journal of Cognition and Neuroethics](http://jcn.cognethic.org/jcnv3i1_Cogley.pdf){target="_blank"} 3, no. 1: 121–37. Archive at [PhilPapers](https://philpapers.org/rec/COGRBT){target="_blank"} 
* **Basic Desert of Reactive Emotions.** 2013. [Philosophical Explorations](https://www.tandfonline.com/toc/rpex20/16/2?nav=tocList){target="_blank"} 16, no. 2: 165–77. Reprinted in Basic Desert, Reactive Attitudes and Free Will, edited by Maureen Sie and Derk Pereboom, 69-81. New York: Routledge, 2016. Archive at [PhilPapers](https://philpapers.org/rec/COGBDO){target="_blank"}
* **Trust and the Trickster Problem.** 2012. [Analytic Philosophy](https://onlinelibrary.wiley.com/toc/2153960x/2012/53/1){target="_blank"} 53, no. 1: 30–47. Archive at [PhilPapers](https://philpapers.org/rec/COGTAT){target="_blank"}

### CHAPTERS IN EDITED COLLECTIONS
* **Contempt’s Evaluative Presentation and Connection to Accountability.** 2018. In [The Moral Psychology of Contempt](https://rowman.com/ISBN/9781786604163/The-Moral-Psychology-of-Contempt){target="_blank"}. Michelle Mason, ed. Lanham, MD, Rowman and Littlefield. Archive at [PhilPapers](https://philpapers.org/rec/COGCEP){target="_blank"}
* **A Study of Virtuous and Vicious Anger.** 2014. In [Virtues and Their Vices](https://academic.oup.com/book/2925?login=false){target="_blank"}, edited by Kevin Timpe and Craig Boyd, 199–224. New York: Oxford University Press. Archive at [PhilPapers](https://philpapers.org/rec/COGASO){target="_blank"}
* **The Three-Fold Significance of the Blaming Emotions.** 2013. In [Oxford Studies in Agency and Responsibility](https://global.oup.com/academic/product/oxford-studies-in-agency-and-responsibility-9780199694860?lang=en&cc=us#){target="_blank"}, edited by David Shoemaker, 205–24. New York: Oxford University Press. Archive at [PhilPapers](https://philpapers.org/rec/COGTTS){target="_blank"}

### BOOK REVIEWS
* **Review of Manuel Vargas’s Building Better Beings: A Theory of Moral Responsibility.** [Social Theory and Practice](https://www.pdcnet.org/soctheorpract/content/soctheorpract_2016_0042_0001_0205_0211){target="_blank"}, 2016. Archive at [PhilPapers](https://philpapers.org/rec/COGMVB){target="_blank"}
* **Review of Michael McKenna’s Conversation and Responsibility.** [Philosophy in Review](https://journals.uvic.ca/index.php/pir/article/view/12832){target="_blank"}, 2013. Archive at [PhilPapers](https://philpapers.org/rec/COGMMC){target="_blank"}
* [**Review of Tamler Sommers’ Relative Justice: Cultural Diversity, Free Will, and Moral Responsibility.**](https://ndpr.nd.edu/reviews/relative-justice-cultural-diversity-free-will-and-moral-responsibility/){target="_blank"}
Notre Dame Philosophical Reviews, 2012. Archive at [PhilPapers](https://philpapers.org/rec/COGMMC){target="_blank"}

