---
title: "Teaching"
---

I've been fortunate to have the opportunity to teach outstanding students at [Northern Michigan University](https://nmu.edu){target="_blank"}, [UCLA](https://ucla.edu){target="_blank"}, [The Ohio State University](https://www.osu.edu){target="_blank"}, and [University of Cincinnati](https://www.uc.edu){target="_blank"}. Practice making complex philosophical concepts accessible to students jump started my ability to translate between techinical experts and clients without substantial technical background. 

# COURSES TAUGHT
## UPPER LEVEL
###### NMU
* Philosophy of Mind
* Moral Responsibility, Free Will, and Punishment
* Ancient and Medieval Philosophy
* Philosophy and Psychology of Emotion
* Philosophy and Psychology of Emotion (Honors)
* Social and Political Philosophy

###### UCLA
* Medical Ethics
* Society and Morals
* Early Modern Political Philosophy
* Philosophy of Law

###### OSU
* Contemporary Social and Moral Problems in the United States

## INTRODUCTORY LEVEL
###### NMU
* Introduction to Logic
* Fundamentals of Ethical Theory
* Issues in Legal Ethics
* Issues in Business Ethics
* Issues in Medical Ethics
* Issues in Computer Ethics

###### UCLA
* Introduction to Ethical Theory

###### Ohio State
* Introduction to Ethics
* Political and Social Philosophy

###### Cincinnati
* Introduction to Ethics

## TEACHING ASSISTANT
###### Ohio States
* Philosphy of Law
* Ancient Greek Philosophy
* Philosophy of Religion
* Symbolic Logic
* Probability, Data, and Decision Making
* Introduction to Philosophy

###### Cincinnati
Symbolic Logic
